In [20]:
import pandas
import os
import numpy as np

In [2]:
def make_dataframe(pickle_data):
    return(pandas.read_pickle(pickle_data, compression='infer', storage_options=None))



In [3]:
directory = os.fsencode("reduced_supervised_data")

frames = []    
for id, file in enumerate(os.listdir(directory)):
     filename = os.fsdecode(file)
     if filename.endswith(".xz"): 
         frames.append(make_dataframe("reduced_supervised_data/"+filename))
         continue
     else:
         continue

In [4]:
print(frames[0])
print(frames[1])

(array([[[0.1       , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.14285715, 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.11111111, 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.11111111, 0.125     ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.07124705, 0.07692308],
        [0.05234239, 0.05234239],
        [0.07692308, 0.07124705],
        [0.        , 0.        ],
        [1.        , 1.        ],
        [0.        , 1.        ],
        [0.        , 0.        ],
        [1.        , 0.        ],
        [0.        , 0.        ]]]), 0, -1)
(array([[[0.        , 0.        ],
        [0.16666667, 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ],
  

In [23]:
frames_flat = frames[0][0][:,:,1].flatten


In [24]:
len(frames)

8185

In [26]:
frames[0][0][:,:,1].shape

(1, 25)

In [47]:
frames[1][0][:,:,1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.1       , 0.        , 0.        , 0.        ,
        0.        , 0.16439899, 0.12803688, 0.23570226, 0.        ,
        1.        , 1.        , 0.        , 0.        , 0.        ]])

In [29]:
frames_array = np.zeros((len(frames), 25))

In [33]:
frames_array[0] = frames[0][0][:,:,1]

In [39]:
for i in range(len(frames)):
    print(frames[i][0][:,:,1])
    frames_array[i] = frames[i][0][:,:,1]

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.125
  0.         0.         0.         0.         0.07692308 0.05234239
  0.07124705 0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.1
  0.         0.         0.         0.         0.16439899 0.12803688
  0.23570226 0.         1.         1.         0.         0.
  0.        ]]
[[0.33333334 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         1.         1.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.2        0.         0.
  0.         0.         0.         0.         0.125      0.06142951
  0.06984303 0.         0. 

[[0.         0.         0.33333334 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.5        0.2
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.14285715
  0.         0.         0.         0.         0.2        0.4472136
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.31622777 0.70710678
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.5        0.
  0.5        0.         0.11111111 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.     

  0.  0.  0.  0.  1.  1.  0. ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.25       0.
  0.         0.         0.         0.         0.23570226 0.4472136
  0.2236068  0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.24253563 0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  0.]]
[[0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  0.  0.  0. ]]
[[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.125 0.
  0.    0.    0.    0.    0.    0.    0.    0.    1.    1.    0.    0.
  0.   ]]
[[0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0. ]]
[[0.  0.

  1.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         1.         0.         0.         0.         0.16666667
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.11111111 0.         0.         0.         0.25       0.
  0.         0.         0.         0.         0.11043153 0.07905694
  0.09407209 0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.11111111 1.         0.
  0.         0.         0.         0.         0.2236068  0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.
  0.]]
[[0.         0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.16666667 0.1666

  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.08333334
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0.]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.25
  0.         0.         1.         0.         0.2773501  0.0766965
  0.09712859 0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.1        0.
  0.         0.         0.09090909 0.         0.         0.33333334
  0.         0.         0.         0.         0.07432941 0.11704115
  0.11704115 0.         0.         0.         0.         0.
  0.        ]]
[[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.125
  0.    0.    0.    0.    0.    

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.33333334 0.11111111 0.         0.14285715
  0.         0.         0.         0.         0.13867505 0.
  0.         0.         0.         0.         0.         0.
  1.        ]]
[[0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.4472136 0.        0.        0.        0.
  0.        1.        1.        0.       ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1.]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.33333334 1.         0.         0.14285715
  0.         0.         0.         0.33333334 0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.         0.5
  0.         0.         0.       

  0.  0.  0.  1.  0.  0.  0. ]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.
  0.]]
[[0.         0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.16666667
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.2        0.5        0.09245003
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.16666667 0.         0.         0.         0.
  0.         0.         0.         0.11111111 0.         0.
  0.         0.         0.         0.         0.25       0.
  0.         0.         0.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.16666667 0.         

[[1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.4472136  0.09284767
  0.         0.         0.         0.         0.         1.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.125      0.         0.
  0.         0.         0.         0.         0.05652334 0.08333333
  0.07071068 0.         0.         0.         1.         1.
  0.        ]]
[[0.         1.         0.         0.07692308 0.         0.
  0.         0.         0.         0.2        0.         0.08333334
  0.         0.16666667 0.         0.         0.09950372 0.06726728
  0.07124705 0.         0.         0.         0.         1.
  0.        ]]
[[0.        0.        0.5       0.        0.        0.        0.
  0.        0.        0.        0.        0.1       0.        0.
  0.        0.        0.2773501 1.        0.        0.        1.
  1.    

  0.        ]]
[[0.         0.         0.         0.         1.         0.
  0.         0.         0.08333334 0.         0.         0.
  0.         0.         0.         0.         0.25       0.70710678
  0.1118034  0.         0.         0.         1.         1.
  1.        ]]
[[0.         0.125      0.         0.         0.         0.
  0.         0.         0.33333334 0.5        0.125      0.2
  0.         0.         0.         0.25       0.15811388 0.35355339
  0.16666667 0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.5        0.         0.         0.         0.
  0.         0.         0.         0.07692308 0.         0.
  0.         0.         0.         0.         0.13130643 0.
  0.         0.         0.         0.         1.         1.
  0.        ]]
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.
  0.  0.  0.  0.  0.  1.  0. ]]
[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.
  0.   0.   0.5  0.   0.   0

[[1.         0.         0.         0.         0.         0.
  0.         0.         0.1        0.         0.         0.
  0.         0.         0.         0.         0.4472136  0.24253563
  0.         0.         0.         0.         1.         1.
  0.        ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.16666667
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.14142136 0.
  0.         0.         0.         0.         1.         1.
  0.        ]]
[[0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.    

[[0.         0.         0.         0.5        0.         0.
  0.         0.         0.07692308 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.33333333 0.
  0.         0.         1.         1.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.33333334 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.33333334 0.         0.         0.         0.
  0.         0.         0.         0.         0.70710678 0.24253563
  0.         0.         1.         1.         0

In [40]:
from sklearn.decomposition import PCA

In [43]:
pca = PCA(n_components=10)

In [44]:
pca.fit(frames_array)

PCA(n_components=10)

In [45]:
print(pca.explained_variance_ratio_)
###results:
#[0.39468725 0.16229801 0.06117051 0.05700383 0.03500299 0.03007792
# 0.02725023 0.02556418 0.02464933 0.02260014]


[0.39468725 0.16229801 0.06117051 0.05700383 0.03500299 0.03007792
 0.02725023 0.02556418 0.02464933 0.02260014]
